#!/bin/bash
#
# your job's name
#$ -N L4AKE_1
#
# shell for execution
#$ -S /bin/bash
#
# SGE queue
#$ -q parallel.q@n121
#
# pe request
#$ -pe fill_up 32
#
# work from current working directory
#$ -cwd
#
# set output file
#$ -o ./4AKE_out
#
# set error file
#$ -e ./4AKE_err
#
# SGE allocated nodes
# Prepare nodelist file for charmrun ...

# Previous script
# /usr/local/NAMD/NAMD_2.8_Linux-x86_64-multicore/namd2 molcom.conf > molcom.log



namd2 +p$NSLOTS 4AKE.conf > 4AKE.log

exit 0
