#!/bin/bash
#
# your job's name
#$ -N H1AKE_1
#
# shell for execution
#$ -S /bin/bash
#
# SGE queue
#$ -q parallel.q@@bahar64
#
# pe request
#$ -pe fill_up 16
#
# work from current working directory
#$ -cwd
#
# set output file
#$ -o ./1AKE_out
#
# set error file
#$ -e ./1AKE_err
#
# SGE allocated nodes
# Prepare nodelist file for charmrun ...

# Previous script
# /usr/local/NAMD/NAMD_2.8_Linux-x86_64-multicore/namd2 molcom.conf > molcom.log



namd2 +p$NSLOTS 1AKE.conf > 1AKE.log

exit 0

